version: '3.8'
services:
  ###### Nhat
  oidc-provider:
    build: ./sso-providers/oidc-provider
    container_name: oidc-provider
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./sso-providers/oidc-provider/realms:/opt/keycloak/data/import
    command: >
      start-dev
      --hostname=http://localhost:9090
      --hostname-strict=false
      --import-realm

  oidc-backend:
    build: ./app/oidc/backend
    container_name: oidc-backend
    ports:
      - "8081:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - OIDC_ISSUER=http://oidc-provider:8080/realms/demo
      - OIDC_CLIENT_ID=oidc-demo
      - OIDC_CLIENT_SECRET=demosecret
      - OIDC_REDIRECT_URI=http://localhost:8081/callback
      - OIDC_PUBLIC_ISSUER=http://localhost:9090/realms/demo

      - SESSION_SECRET=dev-secret
    depends_on:
      - oidc-provider
      - redis
    command: sh -c "sleep 55 && node index.js"

  oidc-frontend:
    build: ./app/oidc/frontend
    container_name: oidc-frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://oidc-backend:8080
    depends_on:
      - oidc-backend
  #####-----------------------


  #### Cuong
  ####----------------------

  #### Minh
  ####----------------------

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"